"""dashboard/components/report_interface.py — Report viewer and PDF downloader."""

import json
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

# Resolve repo root
ROOT = Path(__file__).resolve().parent.parent.parent


def render(asset: str, cfg: dict) -> None:
    st.subheader("AI-Generated Risk Report")
    st.caption("Reports are generated by the OpenAI API. The LLM interprets pre-computed model outputs only.")

    reports_dir = ROOT / cfg["llm"]["reports_dir"]
    safe        = asset.replace("^", "").replace("-", "_")
    asset_dir   = reports_dir / safe

    jsons = sorted(asset_dir.glob("report_*.json"), reverse=True) if asset_dir.exists() else []
    pdfs  = sorted(asset_dir.glob("report_*.pdf"),  reverse=True) if asset_dir.exists() else []

    col1, col2 = st.columns([3, 1])
    with col1:
        st.markdown(f"**Asset:** {asset}")
        if jsons:
            ts = jsons[0].stem.replace("report_", "")
            st.markdown(f"**Reports stored:** {len(jsons)}  |  **Latest:** {ts[:8]} {ts[9:15]} UTC")
        else:
            st.info(f"No reports yet. Run: `python scripts/generate_report.py --asset {asset}`")

    with col2:
        if pdfs:
            st.download_button(
                "Download Latest PDF",
                data=pdfs[0].read_bytes(),
                file_name=pdfs[0].name,
                mime="application/pdf",
            )

    if not jsons:
        return

    st.markdown("---")
    report = json.loads(jsons[0].read_text("utf-8"))
    st.markdown(report.get("report_text", ""))

    with st.expander("Input Payload"):
        st.json(report.get("payload", {}))

    with st.expander("Report Metadata"):
        st.json({
            "model":         report.get("model"),
            "generated_at":  report.get("generated_at"),
            "input_tokens":  report.get("input_tokens"),
            "output_tokens": report.get("output_tokens"),
        })

    if len(jsons) > 1:
        st.markdown("---")
        st.subheader("Report History")
        rows = []
        for f in jsons[:15]:
            d = json.loads(f.read_text("utf-8"))
            p = d.get("payload", {})
            rows.append({
                "Generated":  d.get("generated_at", "")[:19].replace("T", " "),
                "Risk Score": p.get("risk_score"),
                "Band":       p.get("risk_band"),
                "Regime":     p.get("current_regime"),
            })
        st.dataframe(pd.DataFrame(rows), use_container_width=True)
